language: python
python:
- '3.6'
branches:
  only:
  - foobar
before_script:
- pip install -r requirements.txt
script:
- pytest --cov=organact --cov=core

notifications:
  email:
    recipients:
      secure: qCjP7h98raUSRJAQayT7w6JuVnjqOxiwB6KPZWY+9cLrjfmGjvhOkgZ7iyE4o+VRwxwK7NgW60nDKS8kLbv+pnlQAIoc1KdvCi5SnY/QoD5b9rJVcRuFdfmrdv2jcssnwjoVJZO2sGd7+CK9R++SzCKmjnjUseQyDA6VBLvRrrwmGvWNPXKpB3Dv/Oktdxy9ET21cg7yOF4HAENcASzZ8i+URXb/xNklTz3NcBiSA4tWiGh+a635x5f9CAByHAQQO1cBWopK4RMYbNA/90B9SEme1Jh4vmcrTFvSK8C3EG0YVbwOeRdSARC2jfgTEXXMpUWmSiuVh08iqCFMqWK4MdfGqi+cW8eQQij6dZxFyuG3WhtHVS5i6nK1YQx/O3iNJ+5kdaV47ng3aozFz8diOouq3aRytWiXbhQHeKbJ+XiEeyMOLtrFYzwRaPACDFsGHi0DKKq1gmVdmiDy/A0k1GBcCRcy3MrqgN91cOhldK4h/txwC9AMiXkrulf5+2N/iALXqF9lpk+apJqs9MuuVJKix9vwB+pqp/uQXa13kIvQvpraGHdQfVKdhpWUxd0UvUr13SMeYpsmLwjjhEgU+yVQ2PHjgG7VgyVFeRzhn6HU4Ato3PwEZ3HBkGLSmpOJoDcR9dAorUrNrGB5nMFsWMiYxTdG62W4sQPWJ+ff6Zc=
    on_success: always
    on_failure: never
