language: python

python:
- '3.6'

addons:
  postgresql: "9.6"

branches:
  only:
  - foobar

before_script:
- pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="core.settings.travis"

script:
- pytest --cov=a14n --cov=core

after_success:
- coveralls

deploy:
  provider: heroku
  app: ocp13-1664
  on:
    repo: freezed/ocp13
    branch: foobar
  api_key:
    secure: VGkEi0BPjWVqlywfpm/XFA82pl0bJ7EWFtUhvyUOThMQTQNp1DAZUem26AdkOdLo4Shqs9DxR1+UI59VpKNa2Ilix5+JKBNIAdtOgzHdcCDNUp3bPYwdbJKUUpp6yjmuSCQvwWmY5ID0qUW6S6Xss6tIGHE2DYipnmuN4E+htY43d3JjXotkvRkbhI9nSbbmbBDai4BnutYOtYqcC54kLR3KTbvpNyNGSeOwlmKmm3BIc2RJg4TcjeOnWgDBSfyWjAlO51JLo1of2P4nq1AuYp+hhobQlaYLDrPRkx8KTveBK2720ZDPkTIPNwz9SYKDFgis7hgqjdjbBYmy0vgWNvWpG7JIZhw02YJ9zNXmfjlcaNheemcLLRRLhIsVtRgZN9tVGO6Zl9etM7PyQGtamv/oU2sUTcZguaePfVrvW4AtrgS/mWcp8QfUmBTt6iq8TunDLxmccatbKWESK2+LdlEU35vytR8xGHTHPVXyKQt6F2fC/McIeDPKatfnyp2F5O8+uqhdd4Gbod1poASngsxskCThuYzWxwzTMMex+h3MSos785phsqbLvcpnw39MkMBNd96jYDwhko9QYBS78/m5BueUh1AZukIsIpxmrEz7kCDKzOr/Doq9iqNJeZbFaN9vQuflhR/Ls0i0hG22RkcbwGAjB0Le2n1dFxMRfbA=
